# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ac2b8539fbf903745b4fcbb0eed606e415ce17f774996aca5ae872cc7b98ad0631e7a8b0a1b04d3bf4c20c29cf95d5775c24e5d46e917fc1f7d5cf18bfb76a

test:
  secret_key_base: 190fd0b1e7fb46fa548dc8666e4c8a6f23a9d95d1725e72340fffe5e97d4af8a1d071476762b58aaa2169739391891373e6a2eb1c04da67b24e260ec8c14542f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
